### ISSUE TITLE
Card Distribution Error

### ISSUE THREAD

**Issue by kulcsarrudolf** [Kulcsarzsolt/take6#1]
Sometimes the distribution of cards is not working as expected.

```
Exception in thread "pool-1-thread-1" java.lang.IndexOutOfBoundsException: Index: 100, Size: 100
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at Nimmt6.Deck.getCards(Deck.java:53)
	at Nimmt6.Deck.getTenRandomCard(Deck.java:45)
	at Nimmt6.Game.addNewPlayer(Game.java:26)
	at Nimmt6.ClientHandler.run(ClientHandler.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Kulcsarzsolt** [comment]
**Fixed.**
